### PR TITLE
Comment pop up with selected items

### PR DESCRIPTION
**Pull request by Kossi-stack**
**In this pull request**
We add the comment pop up with selected items details

### CODE REVIEW

**Comment by yaseerokino** [comment]
Approved👏
Hi @Kossi-stack,
Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

Cheers and Happy coding!👏👏👏

**Review by ookino — APPROVED** [review]
Approved👏
Hi,
Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

Cheers and Happy coding!👏👏👏

**Review by lily-coder — APPROVED** [review]
### Approved 👏
Congratulations! 🎉
We are almost there
Now its time to merge it

**Review by lily-coder — COMMENTED** [review]
Good work

**Pull request merged**
